# Generated by Django 4.2.7 on 2023-12-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transction',
            new_name='Transaction',
        ),
    ]
