# Generated by Django 4.2.7 on 2024-01-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_transferdestination_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdestination',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransferDestination',
        ),
    ]
