# Generated by Django 4.2.7 on 2024-01-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdestination',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
